#!/bin/bash

get_volume() {
	while true; do
		# Get the volume percentage
		pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]\{1,3\}%' | head -n1 | tr -d '%'
		sleep 1
	done
}

set_volume() {
	pactl set-sink-volume @DEFAULT_SINK@ "$1%"
}

if [[ "$1" == "--set-volume" ]]; then
	set_volume "$2"
else
	get_volume
fi
